// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7F35JTawcRFpu_TF-a6sdAhJPPM8LTBc',
    appId: '1:801554956979:web:827510e93762ae1a7c66c6',
    messagingSenderId: '801554956979',
    projectId: 'login-speakup',
    authDomain: 'login-speakup.firebaseapp.com',
    storageBucket: 'login-speakup.appspot.com',
    measurementId: 'G-LMNZHSW64Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzeOLqYvSwb5iOQtoaOOO1_suzecl9yjk',
    appId: '1:801554956979:android:f72963e4ebcd65e47c66c6',
    messagingSenderId: '801554956979',
    projectId: 'login-speakup',
    storageBucket: 'login-speakup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGbxLRas9pNX8tBqw8t5xjKvB70OfX3kc',
    appId: '1:801554956979:ios:5eed7f0d21062f107c66c6',
    messagingSenderId: '801554956979',
    projectId: 'login-speakup',
    storageBucket: 'login-speakup.appspot.com',
    iosClientId: '801554956979-hd8qioj328010k34lmkrk3nta76p4l4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGbxLRas9pNX8tBqw8t5xjKvB70OfX3kc',
    appId: '1:801554956979:ios:5eed7f0d21062f107c66c6',
    messagingSenderId: '801554956979',
    projectId: 'login-speakup',
    storageBucket: 'login-speakup.appspot.com',
    iosClientId: '801554956979-hd8qioj328010k34lmkrk3nta76p4l4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakup',
  );
}
